/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
//export type { MasterChef } from "./MasterChef";
//export type { SusuMagic } from "./SusuMagic";
//export type { SusuParty } from "./SusuParty";
//export type { SusuToken } from "./SusuToken";

import ORCHESTRATOR_ABI from './Orchestrator.json'
import CHEF_ABI from './MasterChef.json'
import MAGIC_ABI from './SusuMagic.json'
import SUSU_ABI from './SusuToken.json'
import PARTY_ABI from './SusuParty.json'
import QUERY_ABI from './SusuQuery.json'
import STAKING_GAME_ABI from './StakingGame.json'
import STAKING_GAME_QUERY_ABI from './StakingGameQuery.json'
import COLLECTION_S1_ABI from './Collection.json'

export {CHEF_ABI, MAGIC_ABI, SUSU_ABI, PARTY_ABI, QUERY_ABI, ORCHESTRATOR_ABI, STAKING_GAME_ABI, STAKING_GAME_QUERY_ABI, COLLECTION_S1_ABI}
